// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/Articles/Article.vue')['default']
    Latest: typeof import('./src/components/Articles/Latest.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./src/components/button/Tag.vue')['default']
    ToTopBtn: typeof import('./src/components/button/ToTopBtn.vue')['default']
  }
}

export {}
